### ISSUE TITLE
FF_Sleep in IOMan always skipped

### ISSUE THREAD

**Issue by Eriobis** [FreeRTOS/FreeRTOS-Labs#7]
Hi,
I was exploring the code to find why my code is slowish and I can't download with filezilla more than 300k sec, and I ran into this little bug :

```
if( FF_GETERROR( slRetVal ) != FF_ERR_DRIVER_BUSY )
{
   break;
}
```

The following FF_Sleep and while(1) can never occur since we are comparing slRetVal & 0xFFFF and a full uint32_t constant.

I think

```
if(  slRetVal  != FF_ERR_DRIVER_BUSY )
{
   break;
}
```

should make the jobs.

Cheers,

**Comment by htibosch** [comment]
Thanks a lot @Eriobis for reporting this.
I had never noticed this because none of the FreeRTOS+FAT drivers have an access function that can return `FF_ERR_DRIVER_BUSY`.

**Comment by muneebahmed10** [comment]
I will close this issue as https://github.com/FreeRTOS/Lab-Project-FreeRTOS-FAT/pull/19 has been merged
